name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: yats-client-linux-amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: yats-client-macos-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: yats-client-windows-amd64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}
        working-directory: ./client

      - name: Rename binary
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            mv ./client/target/${{ matrix.target }}/release/yats-client.exe ./client/target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          else
            mv ./client/target/${{ matrix.target }}/release/yats-client ./client/target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          fi

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./client/target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
