name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build client
      run: cargo build --verbose
      working-directory: ./client
    - name: Run client tests
      run: cargo test --verbose
      working-directory: ./client
    - name: Build server
      run: cargo build --verbose
      working-directory: ./server
    - name: Run server tests
      run: cargo test --verbose
      working-directory: ./server
